### PR TITLE
Fix heredoc comma issue

### LINKED ISSUE #61: Heredoc hash values have errant comma
Hiya! Came across this issue when testing rufo's changes to a codebase. Rufo adds a trailing comma to hash args, which can break heredocs, as follows:

```ruby
{
  content: <<-EOF
    This is a heredoc
  EOF
}
```

...gets transformed to
```ruby
{
  content: <<-EOF
    This is a heredoc
  EOF,
]
```

Which will yield the error:
```shell
test.rb:5: can't find string "EOF" anywhere before EOF
test.rb:2: syntax error, unexpected end-of-input, expecting tSTRING_CONTENT or tSTRING_DBEG or tSTRING_DVAR or tSTRING_END
```

In cases of heredocs, commas simply can't be placed without breaking the terminator.

### PR DESCRIPTION
**Pull request by gingermusketeer**
Fixes #61.

### CODE REVIEW

File: lib/rufo/formatter.rb [hunk 1]
```diff
@@ -574,7 +582,20 @@ def visit_string_literal(node)
       # Accumulate heredoc: we'll write it once
       # we find a newline.
       @heredocs << [node, tilde]
-      next_token
+      # Get the next_token while capturing any output.
+      # This is needed so that we can add a comma if one is not already present.
+      captured_output = capture_output { next_token }
+
+      inside_literal_elements_list = !@literal_elements_level.nil? &&
```
Comment (splattael) [inline lib/rufo/formatter.rb]: Should we initialize `@literal_elements_level` in the `initialize` method similar to `@node_level`?

Comment (gingermusketeer) [reply lib/rufo/formatter.rb]: Good call. I have fixed this up.

**Comment by gingermusketeer** [comment]
Any other thoughts on this one?
